development:
  adapter: postgresql
  host: localhost
  port: 5432
  database: sinatra_postgres_dev
  username: postgres
  password: ankit1234


production:
  adapter: postgresql            
  host: 192.168.2.53                          # VM IP
  port: 7156                          # VM Port 
  database: t             # Database Name
  username: ac5lg3rg2tan43g3                 # User Name
  password: 'aq3dh5j1xdk7ny7npq0585ih9y11f72a'                # password
