development:
  adapter: postgresql
  host: localhost
  port: 5432
  database: sinatra_postgres_dev
  username: postgres
  password: ankit1234


production:
  adapter: postgresql            
  host: 192.168.2.202                          # VM IP
  port: 26737                          # VM Port 
  database: t             # Database Name
  username: a3kuyomtyhn1c2ul                 # User Name
  password: 'atz0dxtrma0vcw18oh6ucwohs2j9d01p'                # password
